name: uvtt
description: Universal VTT File reader
publish_to: 'none'
version: 0.8.0

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_selector: ^0.8.4+1
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.0
  path: ^1.8.1
  firebase_analytics: ^9.1.7
  firebase_core: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/github_icon.webp
  uses-material-design: true
