// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUpD8Y5y50antdXLJ5w5Ki2RWm2-arcE',
    appId: '1:253013501608:web:e6ac2a807c88d04349849d',
    messagingSenderId: '253013501608',
    projectId: 'csells-uvtt',
    authDomain: 'csells-uvtt.firebaseapp.com',
    storageBucket: 'csells-uvtt.appspot.com',
    measurementId: 'G-GRSSL9E84M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAveGMoa8FmGWfijz_ITix95ToR0me6nZo',
    appId: '1:253013501608:ios:34de5d72508372df49849d',
    messagingSenderId: '253013501608',
    projectId: 'csells-uvtt',
    storageBucket: 'csells-uvtt.appspot.com',
    iosClientId: '253013501608-lq7fsfibjp5e87vc20v70s495a5pv4ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.uvtt',
  );
}
